# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='iva',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
