# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_auto_20180530_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lista',
            old_name='subtotal',
            new_name='importe',
        ),
        migrations.AddField(
            model_name='pedido',
            name='subtotal',
            field=models.FloatField(null=True),
        ),
    ]
