# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_auto_20180530_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='aprobacion',
            field=models.BooleanField(default=False),
        ),
    ]
