# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='email',
            field=models.EmailField(default='email@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo',
            field=models.CharField(choices=[('IC', 'Ingeniero civil'), ('AM', 'Administrador de materiales'), ('AU', 'Administrador de usuarios')], default='IC', max_length=2),
            preserve_default=False,
        ),
    ]
