# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_auto_20180531_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='tipo',
            field=models.CharField(choices=[('IC', 'Ingeniero civil'), ('AE', 'Administrador de empleados'), ('AM', 'Administrador de materiales'), ('AS', 'Administrador del sistema')], max_length=2),
        ),
    ]
