# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_auto_20180531_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='apellido',
            new_name='apellido_materno',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='apellido_paterno',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='numero',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
