# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puestos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puesto',
            name='tipo_contrato',
            field=models.CharField(choices=[('B', 'Base'), ('C', 'De confianza')], max_length=1),
        ),
    ]
